<predicates>
calibrated-camera0-rover0,available-rover0,have_image-rover0-objective0-colour,have_rock_analysis-rover0-waypoint1,have_rock_analysis-rover0-waypoint2,communicated_rock_data-waypoint2,have_rock_analysis-rover0-waypoint3,communicated_rock_data-waypoint3,at-rover0-waypoint3,at-rover0-waypoint2,communicated_rock_data-waypoint1,at-rover0-waypoint1,communicated_image_data-objective0-high_res,have_soil_analysis-rover0-waypoint0,at_soil_sample-waypoint2,at-rover0-waypoint0,at_soil_sample-waypoint3,at_soil_sample-waypoint0,have_soil_analysis-rover0-waypoint2,calibrated-camera0-rover0-waypoint0,have_soil_analysis-rover0-waypoint3,calibrated-camera0-rover0-waypoint1,have_image-rover0-objective1-colour,communicated_image_data-objective1-colour,communicated_image_data-objective0-colour,have_image-rover0-objective0-high_res,communicated_soil_data-waypoint3,communicated_soil_data-waypoint2,channel_free-general,have_image-rover0-objective1-high_res,empty-rover0store,communicated_soil_data-waypoint0,communicated_image_data-objective1-high_res,calibrated-camera0-rover0-waypoint2,calibrated-camera0-rover0-waypoint3,full-rover0store,at_rock_sample-waypoint1,at_rock_sample-waypoint3,store_of-rover0store-rover0,at_rock_sample-waypoint2,
<\predicates>
<constraints>
at-rover0-waypoint3,at-rover0-waypoint2,at-rover0-waypoint1,at-rover0-waypoint0,empty-rover0store,full-rover0store,
<\constraints>
<initial>
at-rover0-waypoint2
<\initial>
<goal>
at-rover0-waypoint3,
<\goal>
<preferences>
always-at_soil_sample-waypoint0
<\preferences>
<actionsSet>
<action>
<name>navigate-waypoint2-waypoint1-waypoint3<\name>
<pre>at-rover0-waypoint2,available-rover0<\pre>
<pos>~at-rover0-waypoint2,at-rover0-waypoint1:~at-rover0-waypoint2,at-rover0-waypoint3<\pos>
<\action>
<action>
<name>navigate-waypoint0-waypoint3<\name>
<pre>at-rover0-waypoint0,available-rover0<\pre>
<pos>~at-rover0-waypoint0,at-rover0-waypoint3<\pos>
<\action>
<action>
<name>navigate-waypoint1-waypoint2<\name>
<pre>at-rover0-waypoint1,available-rover0<\pre>
<pos>~at-rover0-waypoint1,at-rover0-waypoint2<\pos>
<\action>
<action>
<name>navigate-waypoint1-waypoint3<\name>
<pre>at-rover0-waypoint1,available-rover0<\pre>
<pos>~at-rover0-waypoint1,at-rover0-waypoint3<\pos>
<\action>
<action>
<name>navigate-waypoint3-waypoint0<\name>
<pre>at-rover0-waypoint3,available-rover0<\pre>
<pos>~at-rover0-waypoint3,at-rover0-waypoint0<\pos>
<\action>
<action>
<name>navigate-waypoint3-waypoint1<\name>
<pre>at-rover0-waypoint3,available-rover0<\pre>
<pos>~at-rover0-waypoint3,at-rover0-waypoint1<\pos>
<\action>
<\actionsSet>
