<predicates>
at-rover0-waypoint9,at-rover0-waypoint8,available-rover0,empty-rover0store,full-rover0store
<\predicates>
<constraints>
at-rover0-waypoint9,at-rover0-waypoint8,empty-rover0store,full-rover0store
<\constraints>
<initial>
at-rover0-waypoint9,available-rover0
<\initial>
<goal>
at-rover0-waypoint8
<\goal>
<preferences>
always-available-rover0
<\preferences>
<actionsSet>
<action>
<name>navigate-waypoint8-waypoint9<\name>
<pre>at-rover0-waypoint8,available-rover0<\pre>
<pos>~at-rover0-waypoint8,at-rover0-waypoint9<\pos>
<\action>
<\actionsSet>
